HUGH changes!  I finally converted KAppTemplate to produce KDE 2.x apps instead of 1.x ones.  In addition, I beefed up the amount of cut-n-paste features in the skeleton app -- in fact, it is an actual working app from scratch, now.  Specifically, it creates a web browser -- a SCRIPTABLE web browser (check out dcopclient.py to see how you can get it to remotely load a web page with a python script).
I have only tested this on my machine so it might have some system
specific things.

svn path=/trunk/kdesdk/kapptemplate/; revision=32725

diff --git a/kapptemplate b/kapptemplate
--- a/kapptemplate
+++ b/kapptemplate
@@ -55,9 +55,23 @@ else
 	exit 1;
 fi
 
+if [ -d "$SHARE_DIR/common" ];
+then
+	ADMIN_FILES=`/bin/ls $SHARE_DIR/admin`;
+
+	if [ ! "$ADMIN_FILES" ];
+	then
+		$ECHO "Cannot find admin files in $SHARE_DIR/admin!";
+		exit 1;
+	fi
+else
+	$ECHO "$SHARE_DIR/admin directory does not exist!";
+	exit 1;
+fi
+
 if [ -d "$SHARE_DIR/variable" ];
 then
-	VARIABLE_FILES=`/bin/ls $SHARE_DIR/variable`;
+	VARIABLE_FILES=`/bin/ls -I "no-exe" $SHARE_DIR/variable`;
 
 	if [ ! "$VARIABLE_FILES" ];
 	then
